[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"
external_node_modules = ["googleapis", "lambda-multipart-parser"]
included_files = ["netlify/functions/upload.ts"]

[dev]
targetPort = 5173
functionsPort = 8888
framework = "vite"
